export const GET_ERRORS = "GET_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_EXAMPLE = "GET_EXAMPLE";
export const SET_EXAMPLE = "SET_EXAMPLE";
export const SET_EXAMPLES = "SET_EXAMPLES";
export const ADD_NEW_EXAMPLE = 'ADD_NEW_EXAMPLE';
export const SEARCH_EXAMPLES = 'SEARCH_EXAMPLES';
